# Site settings
name: a11y examples
title: a11y examples
email: jonespe@gmai.com
description: "A bunch of HTML accessibility (a11y) video examples using different screen readers."
baseurl: "/a11y-examples"
url: "http://yourdomain.com"

# Build settings
markdown: kramdown
permalinks: pretty
